# Scientific python (SciPY)

### Scipy sub-packages

#### Integration

In [2]:
#quad integration
from scipy.integrate import quad

In [3]:
def integratefunction(x):
    return x

In [4]:
quad(integratefunction, 0,1)

(0.5, 5.551115123125783e-15)

In [5]:
def integrateFn(x,a,b):
    return x*a+b

In [6]:
a=3
b=2

In [7]:
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [9]:
import scipy.integrate as integrate

In [10]:
def f(x,y):
    return x + y
integrate.dblquad(f, 0,1,lambda x: 0, lambda x:2)

(3.0, 4.436070580899685e-14)

#### optimization

In [11]:
import numpy as np
from scipy import optimize

In [12]:
def f(x):
    return x**2 +5*np.sin(x)

In [13]:
minimaValue=optimize.minimize(f,x0=2, method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [14]:
minimaValueWithoutOpt = optimize.minimize(f,x0=2, method='bfgs')

In [15]:
minimaValueWithoutOpt

      fun: -3.2463942726915196
 hess_inv: array([[0.15445831]])
      jac: array([-4.47034836e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

#### Linear Alegebra

In [16]:
#solving linear systems
from scipy import linalg

lets try to solve 
<p> 2x+3y+z=21</p>
<p> -x+5y+4z=9</p>
<p> 3x+2y+9z=6</p>

In [19]:
numArray=np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [24]:
numArrValue=np.array([21,9,6]) #the = to values

In [26]:
linalg.solve(numArray,numArrValue) #values for x,yand z

array([ 4.95,  4.35, -1.95])

#### Singlar VAlue decomposition

In [27]:
numSvdArray=np.array([[3,5,1],[9,5,7]])

In [28]:
numSvdArray.shape

(2, 3)

In [29]:
linalg.svd(numSvdArray)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

Eigenvalues and Eigenvector

In [31]:
test_rating_data=np.array([[5,8],[7,9]])

In [32]:
eigenValues, eigenVector=linalg.eig(test_rating_data)

In [33]:
first_eigen,second_eigen=eigenValues

In [34]:
print(first_eigen,second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [35]:
print(eigenVector[:,0])

[-0.81220939  0.58336601]


In [36]:
print(eigenVector[:,1])

[-0.63447346 -0.77294465]


#### Statistics

In [38]:
from scipy.stats import norm

In [40]:
norm.rvs(loc=0,scale=1,size=10)

array([-0.82911743, -0.17096903,  0.84013043, -0.52090144,  0.07058396,
        0.95766823, -1.74636563,  0.00800296,  0.62796957, -0.85920705])

In [43]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [44]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18

#### Weave

includes c/c++ into python

#### IO