# Simplilearn: Numpy

In [2]:
import numpy as np

In [3]:
first_numpy_array=np.array([1,2,3,4])

In [4]:
print(first_numpy_array)

[1 2 3 4]


In [5]:
array_with_zeros=np.zeros((3,3))

In [6]:
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array_with_ones=np.ones((3,3))

In [8]:
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
#array with empty
array_with_empty=np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#arange numpy function
np_arange=np.arange(12)

In [11]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
#reshape method to change array
np.reshape(np_arange,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
#linspace for linearly spaced daata elements, To equally divide data
#the first value is where to start, where to finish adn the number of equidistant elements

In [14]:
np_linspace=np.linspace(1,6,5)

In [15]:
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [16]:
#one dimentional array
oneD_array=np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
#two dimentional array
twoD_array=np.reshape(oneD_array,(3,5))

In [18]:
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
#three dimentional array
ThreeD_array=np.arange(27).reshape(3,3,3)

In [21]:
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [22]:
ThreeD_array.ndim

3

In [23]:
ThreeD_array.shape

(3, 3, 3)

In [24]:
ThreeD_array.size

27

In [25]:
ThreeD_array.dtype

dtype('int32')

### Basic operations

In [26]:
first_trial_cyclist=[10,15,17,26]
second_trial_cyclist=[12,11,21,24]

In [27]:
np_Fst=np.array(first_trial_cyclist)

In [28]:
np_Snd=np.array(second_trial_cyclist)

In [29]:
np_Fst+np_Snd

array([22, 26, 38, 50])

#### Mathematical operations

In [30]:
#lets do addition
np.add(45,20)

65

In [31]:
np.subtract(45,22)

23

In [32]:
np_daily_wage=np.array([7,9,13,8,11])*15

In [33]:
print(np_daily_wage)

[105 135 195 120 165]


In [34]:
sum(np_daily_wage)

720

#### Comparison operators

In [35]:
np_weekly_hrs=np.array([23,41,55,47,38])

In [36]:
np_weekly_hrs > 100

array([False, False, False, False, False])

In [37]:
np_weekly_hrs[np_weekly_hrs > 40]

array([41, 55, 47])

In [38]:
np_weekly_hrs[np_weekly_hrs != 40]

array([23, 41, 55, 47, 38])

#### Logical operations

In [39]:
#logical and operation
np_weekly_hrs[np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)]

array([23, 41, 47, 38])

In [41]:
#logical not operation
np_weekly_hrs[np.logical_not(np_weekly_hrs > 30)]
#shows the only value not greater than 30

array([23])

In [43]:
np.logical_not(np_weekly_hrs > 30)

array([ True, False, False, False, False])

#### Indexing

In [55]:
cyclist=np.array([[10,15,17,26],[12,11,21,24]])
print(cyclist)

[[10 15 17 26]
 [12 11 21 24]]


In [45]:
cyclist.ndim

2

In [47]:
cyclist.shape

(2, 4)

In [48]:
cyclist.size

8

In [51]:
first_cyclist=cyclist[0]

In [52]:
#the first list in the 2D array takes index 0
first_cyclist

array([10, 15, 17, 26])

In [57]:
first_cyclist[0]

10

In [58]:
cyclist[0,1]

15

In [59]:
second_cyclist=cyclist[1]

In [60]:
print(second_cyclist)

[12 11 21 24]


In [62]:
cyclist[:,0] #select everything in the [0] index

array([10, 12])

#### Slicing

In [65]:
# : shows inlude all rows
two_cyclist=cyclist[:,1:3]
two_cyclist

array([[15, 17],
       [11, 21]])

In [68]:
#looping through an array
for values in cyclist:
    print(values)

[10 15 17 26]
[12 11 21 24]


#### Indexing with boolean arrays

In [69]:
test_scores=np.array([[83,71,57,63],[54,68,81,45]])

In [70]:
passing_score=test_scores>60

In [71]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [72]:
#to get the values
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [73]:
test_scores[test_scores>50] #direct

array([83, 71, 57, 63, 54, 68, 81])

#### Copy and views

In [74]:
test_scores_copy=test_scores.copy()

In [77]:
test_scores_copy[:,1]=5

In [78]:
print(test_scores_copy)

[[83  5 57 63]
 [54  5 81 45]]


In [79]:
print(test_scores)

[[83 71 57 63]
 [54 68 81 45]]


the copy/deep copy creates a new distinct array copy of the original. Changes not chained to each other

In [81]:
view_test_scores=test_scores_copy.view()

In [85]:
view_test_scores[:,0]=678

In [86]:
print(view_test_scores)

[[678   5  57  63]
 [678   5  81  45]]


In [87]:
print(test_scores_copy)

[[678   5  57  63]
 [678   5  81  45]]


Changing anything in view/shallow copy changes the original array

In [90]:
view_test_scores == test_scores_copy

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Mathematical Functions of numpy

In [91]:
np_sqrt=np.sqrt([2,4,9,16])

In [93]:
print(np_sqrt)

[1.41421356 2.         3.         4.        ]


In [94]:
from numpy import pi
np.cos(0)

1.0

In [95]:
np.sin(pi/2)

1.0

In [96]:
np.cos(pi)

-1.0

In [98]:
np.floor([1.5,1.6,7.1,-4.567,9.9])

array([ 1.,  1.,  7., -5.,  9.])

In [99]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

#### Shape manipulation

We can use split, flatten , resize, reshape, stack

In [100]:
Random_list=np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [101]:
#Ravel flattens the array to 1 d
Random_list.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [102]:
Random_list.size

12

In [103]:
Random_list.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [104]:
Random_list.resize(2,6)

In [105]:
Random_list

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [107]:
x,y=np.hsplit(Random_list, 2)

In [108]:
x

array([[10, 15, 17],
       [12, 11, 21]])

In [109]:
y

array([[26, 13, 19],
       [24, 14, 23]])

In [112]:
Random_list_Again=np.hstack((x,y))

In [113]:
Random_list_Again

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

#### Broadcasting

In [114]:
array_a=np.array([2,3,5,8])
array_b=np.array([.3,.3,.3,.3])

In [115]:
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [116]:
#lets create a varaible with a scaler values
scaler_c=0.3

In [117]:
#lets broadcast
array_a * scaler_c

array([0.6, 0.9, 1.5, 2.4])

To multiply the arrays must have the same shape

#### Linear Alegbra transpose

In [120]:
test_scores=np.array([[83,71,63,57],[54,68,81,45]])

In [121]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [63, 81],
       [57, 45]])

#### Inverse
Inverse elements

In [122]:
#inverse can only be applied to square matrices
inverse_array=np.array([[10,20],[15,25]])

In [123]:
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

#### Trace
Sum of diagonal elements of the array

In [124]:
trace_array=np.array([[10,20],[22,31]])

In [126]:
np.trace(trace_array) #sum of 10 and 31. applied only from left to right. 

41